[workspace]
resolver = "2"
members = ["common", "day*"]

[workspace.dependencies]
color-eyre = "0.6.2"
common = { path = "./common" }
itertools = "0.12.1"
paste = "1.0.14"
pathfinding = "4.11.0"
rayon = "1.10.0"
regex = "1.11.1"
id-arena = "2.2.1"
