edition = "2021"
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
single_line_let_else_max_width = 80
struct_field_align_threshold = 20
use_field_init_shorthand = true
wrap_comments = true
version = "Two"
