[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre.workspace = true
itertools.workspace = true
paste.workspace = true
pathfinding.workspace = true
rayon.workspace = true
